services:
    server:
        image: express-docker
        ports:
            - 5050:5000
    client:
        build: ./client
        ports:
            - 8080:3000
    mongodb:
        image: mongo
